### ISSUE TITLE
Extract xml for Sherpa Models

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#155]
There is an xml file in the specview jar that describes the sherpa models, we need to extract it into the iris package

**Comment by olaurino** [comment]
https://gist.github.com/olaurino/fc937f5f07af429fa774

The following gist contains the xml files needed by the fitting tool.

We can include them statically in the new code but I was wondering whether they should be served by the sherpa-samp service, so that any updates to these files are responsibility of that package.
