### ISSUE TITLE
Put docs into a new git repository

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#165]
And add it to the main repository when it's done and tested.

**Comment by jbudynk** [comment]
Do we want to include the Project Information and/or Project Reports that Cobertura (or JaCoCo) creates in the Iris user docs? 

I would say no, because users don't care about that kind of information. If we want to deploy that info to the website, I would suggest preventing the Project Info/Report menus from expanding in the navigation. See the java-sandbox site for an example of how busy it looks with the default settings.

**Comment by eholum** [comment]
I tend to agree with you. Definitely shouldn't be included in user
documentation... Developers/interested parties can always access it through
the github repository, right?

On Wed, Oct 28, 2015 at 9:55 AM, Jamie Budynkiewicz <
notifications@github.com> wrote:

> Do we want to include the Project Information and/or Project Reports that
> Cobertura (or JaCoCo) creates in the Iris user docs?
>
> I would say no, because users don't care about that kind of information.
> If we want to deploy that info to the website, I would suggest preventing
> the Project Info/Report menus from expanding in the navigation. See the
> java-sandbox site for an example of how busy it looks with the default
> settings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChandraCXC/iris/issues/165#issuecomment-151852481>.
>



-- 
Erik Holum
