### ISSUE TITLE
Remove @Ignore from SED Stacker Tests

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#172]
Once units are in place and things will actually work.

**Comment by olaurino** [comment]
It looks like some tests were hanging not quite because the window were shown, but because UISpec4j was not initialized. When one initializes UISpec4J it will fail when the windows are shown if they were not supposed to be shown. I think this is the correct behavior, and we don't need to do anything with the windows themselves. Nevertheless, I did try to intercept the error dialog box and dismiss them. In that case the tests fail with the exception thrown by the sedstacker, which says that sherpa could not be found.

The first implementation (let UISpec4J fail when an undesired error message is shown) is much simpler and the error message is very clear. The second option (getting rid of the window) is a little bit cleaner but unnecessarily complicated.

@eholum, @jbudynk, do you think I can proceed with option 1?

**Comment by jbudynk** [comment]
Yes, the test should fail if an expected pop-up window isn't shown.

On Wed, Nov 25, 2015 at 12:08 PM, Omar Laurino <notifications@github.com>
wrote:

> It looks like some tests were hanging not quite because the window were
> shown, but because UISpec4j was not initialized. When one initializes
> UISpec4J it will fail when the windows are shown if they were not supposed
> to be shown. I think this is the correct behavior, and we don't need to do
> anything with the windows themselves. Nevertheless, I did try to intercept
> the error dialog box and dismiss them. In that case the tests fail with the
> exception thrown by the sedstacker, which says that sherpa could not be
> found.
>
> The first implementation (let UISpec4J fail when an undesired error
> message is shown) is much simpler and the error message is very clear. The
> second option (getting rid of the window) is a little bit cleaner but
> unnecessarily complicated.
>
> @eholum <https://github.com/eholum>, @jbudynk <https://github.com/jbudynk>,
> do you think I can proceed with option 1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChandraCXC/iris/issues/172#issuecomment-159675152>.
>



-- 
Jamie A. Budynkiewicz
Smithsonian Astrophysical Observatory
Harvard-Smithsonian Center for Astrophysics
100 Acorn Park Dr. R-377 MS-81
Cambridge, MA 02140
