### ISSUE TITLE
Proper Teardown of Smoketests if there's a Keyboard Interrupt

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#201]
Very low priority. Placeholder just if we ever have time to have to ensure that all processes are stopped after a keyboard inerrupt of the Smoketests.

**Comment by olaurino** [comment]
Just to add some context in case I won the lottery (or more likely lost my visa). The bash script that runs Iris starts a number of background processes (sherpa-samp, Iris) and then waits for them (or tries to kill them): if you send a keyboard interrupt to the script, then the background processes will be left on their own and not properly shut down *without user's intervention*. This is more of an issue for the smoketest or the command line interface in general, but it may also be a (smaller) issue for the main Iris application, since interrupting the launcher script probably leaves the main application running. This is an even smaller issue for sherpa-samp, since it is designed to shut down if no hubs are running, so eventually it will shut itself down (but we should look at #61 sooner rather than later because that issue is probably caused by the keep-alive logic).

**Comment by eholum** [comment]
This issue was moved to ChandraCXC/iris-dev#36
